/*
 * Copyright (c) 2018 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cellery-io/mesh-controller/pkg/apis/mesh/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StandardCellLister helps list StandardCells.
type StandardCellLister interface {
	// List lists all StandardCells in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.StandardCell, err error)
	// StandardCells returns an object that can list and get StandardCells.
	StandardCells(namespace string) StandardCellNamespaceLister
	StandardCellListerExpansion
}

// standardCellLister implements the StandardCellLister interface.
type standardCellLister struct {
	indexer cache.Indexer
}

// NewStandardCellLister returns a new StandardCellLister.
func NewStandardCellLister(indexer cache.Indexer) StandardCellLister {
	return &standardCellLister{indexer: indexer}
}

// List lists all StandardCells in the indexer.
func (s *standardCellLister) List(selector labels.Selector) (ret []*v1alpha1.StandardCell, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StandardCell))
	})
	return ret, err
}

// StandardCells returns an object that can list and get StandardCells.
func (s *standardCellLister) StandardCells(namespace string) StandardCellNamespaceLister {
	return standardCellNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// StandardCellNamespaceLister helps list and get StandardCells.
type StandardCellNamespaceLister interface {
	// List lists all StandardCells in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.StandardCell, err error)
	// Get retrieves the StandardCell from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.StandardCell, error)
	StandardCellNamespaceListerExpansion
}

// standardCellNamespaceLister implements the StandardCellNamespaceLister
// interface.
type standardCellNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all StandardCells in the indexer for a given namespace.
func (s standardCellNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.StandardCell, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StandardCell))
	})
	return ret, err
}

// Get retrieves the StandardCell from the indexer for a given namespace and name.
func (s standardCellNamespaceLister) Get(name string) (*v1alpha1.StandardCell, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("standardcell"), name)
	}
	return obj.(*v1alpha1.StandardCell), nil
}
