/*
 * Copyright (c) 2018 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cellery-io/mesh-controller/pkg/apis/mesh/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// WebCellLister helps list WebCells.
type WebCellLister interface {
	// List lists all WebCells in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.WebCell, err error)
	// WebCells returns an object that can list and get WebCells.
	WebCells(namespace string) WebCellNamespaceLister
	WebCellListerExpansion
}

// webCellLister implements the WebCellLister interface.
type webCellLister struct {
	indexer cache.Indexer
}

// NewWebCellLister returns a new WebCellLister.
func NewWebCellLister(indexer cache.Indexer) WebCellLister {
	return &webCellLister{indexer: indexer}
}

// List lists all WebCells in the indexer.
func (s *webCellLister) List(selector labels.Selector) (ret []*v1alpha1.WebCell, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WebCell))
	})
	return ret, err
}

// WebCells returns an object that can list and get WebCells.
func (s *webCellLister) WebCells(namespace string) WebCellNamespaceLister {
	return webCellNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// WebCellNamespaceLister helps list and get WebCells.
type WebCellNamespaceLister interface {
	// List lists all WebCells in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.WebCell, err error)
	// Get retrieves the WebCell from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.WebCell, error)
	WebCellNamespaceListerExpansion
}

// webCellNamespaceLister implements the WebCellNamespaceLister
// interface.
type webCellNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all WebCells in the indexer for a given namespace.
func (s webCellNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.WebCell, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.WebCell))
	})
	return ret, err
}

// Get retrieves the WebCell from the indexer for a given namespace and name.
func (s webCellNamespaceLister) Get(name string) (*v1alpha1.WebCell, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("webcell"), name)
	}
	return obj.(*v1alpha1.WebCell), nil
}
