/*
 * Copyright (c) 2018 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cellery-io/mesh-controller/pkg/apis/mesh/v1alpha1"
	scheme "github.com/cellery-io/mesh-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StandardCellsGetter has a method to return a StandardCellInterface.
// A group's client should implement this interface.
type StandardCellsGetter interface {
	StandardCells(namespace string) StandardCellInterface
}

// StandardCellInterface has methods to work with StandardCell resources.
type StandardCellInterface interface {
	Create(*v1alpha1.StandardCell) (*v1alpha1.StandardCell, error)
	Update(*v1alpha1.StandardCell) (*v1alpha1.StandardCell, error)
	UpdateStatus(*v1alpha1.StandardCell) (*v1alpha1.StandardCell, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StandardCell, error)
	List(opts v1.ListOptions) (*v1alpha1.StandardCellList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StandardCell, err error)
	StandardCellExpansion
}

// standardCells implements StandardCellInterface
type standardCells struct {
	client rest.Interface
	ns     string
}

// newStandardCells returns a StandardCells
func newStandardCells(c *MeshV1alpha1Client, namespace string) *standardCells {
	return &standardCells{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the standardCell, and returns the corresponding standardCell object, and an error if there is any.
func (c *standardCells) Get(name string, options v1.GetOptions) (result *v1alpha1.StandardCell, err error) {
	result = &v1alpha1.StandardCell{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("standardcells").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StandardCells that match those selectors.
func (c *standardCells) List(opts v1.ListOptions) (result *v1alpha1.StandardCellList, err error) {
	result = &v1alpha1.StandardCellList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("standardcells").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested standardCells.
func (c *standardCells) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("standardcells").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a standardCell and creates it.  Returns the server's representation of the standardCell, and an error, if there is any.
func (c *standardCells) Create(standardCell *v1alpha1.StandardCell) (result *v1alpha1.StandardCell, err error) {
	result = &v1alpha1.StandardCell{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("standardcells").
		Body(standardCell).
		Do().
		Into(result)
	return
}

// Update takes the representation of a standardCell and updates it. Returns the server's representation of the standardCell, and an error, if there is any.
func (c *standardCells) Update(standardCell *v1alpha1.StandardCell) (result *v1alpha1.StandardCell, err error) {
	result = &v1alpha1.StandardCell{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("standardcells").
		Name(standardCell.Name).
		Body(standardCell).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *standardCells) UpdateStatus(standardCell *v1alpha1.StandardCell) (result *v1alpha1.StandardCell, err error) {
	result = &v1alpha1.StandardCell{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("standardcells").
		Name(standardCell.Name).
		SubResource("status").
		Body(standardCell).
		Do().
		Into(result)
	return
}

// Delete takes name of the standardCell and deletes it. Returns an error if one occurs.
func (c *standardCells) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("standardcells").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *standardCells) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("standardcells").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched standardCell.
func (c *standardCells) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StandardCell, err error) {
	result = &v1alpha1.StandardCell{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("standardcells").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
